services:
  # 1. Node Backend API Web Service
  - type: web
    name: asf-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: asf-backendd-compasionchristian-738c.i.aivencloud.com
      - key: DB_PORT
        value: 19549
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false

  # 3. Static Frontend Web Site
  - type: web
    name: asf-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "export VITE_API_URL=${VITE_API_URL}/api && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
